fir/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_method, name = 'home'), 
    path('create_draft/', views.create_draft_method, name = 'create_draft'), 
    path('update_draft/<int:id>', views.update_draft_method, name = 'update_draft'),
    path('update_draft_lebel/<int:id>', views.update_draft_label_method, name = 'update_draft_label'),
    path('delete_draft/<int:id>', views.delete_draft_method, name = 'delete_draft'),
    path('report/', views.report_method, name = 'report'), 
    path('report/<int:id>', views.report_method, name = 'report_id'), 
]

project_fir/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index_method, name = 'index'), 
    path('about/', views.about_method, name = 'about'), 
    path('admin/', admin.site.urls), 
    path('contact_us/', views.contact_method, name = 'contact'), 
    path('documantation/', views.docs_method, name = 'docs'), 
    path('fir/', include('fir.urls')), 
    path('privacy/', views.privacy_method, name = 'privacy'), 
    path('redirect/', include('login.urls')), 
    path('resources/', views.resources_method, name = 'resources'), 
    path('tac/', views.tac_method, name = 'tac'), 
    path('test/', views.test_method, name = 'test'), 
    path('user/', include('users.urls'))
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('change_pwd/', views.change_pwd_method, name = 'change_pwd'), 
    path('civilian/', views.civilian_method, name = 'civilian'), 
    path('civilian_edit/', views.edit_c_method, name = 'edit_c'), 
    path('civilian_test/', views.test_c_method, name = 'test_c'), 
    path('officer/', views.officer_method, name = 'officer')
]

fir/models.py
from datetime import datetime
from django.db import models

# Create your models here.

class jurisdictionModel(models.Model):
    division = models.CharField(max_length = 50)
    def __str__(self):
        return self.division

from login.models import civilianModel, officerModel

class reportModel(models.Model):
    division = models.ForeignKey(jurisdictionModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    subject = models.CharField(max_length = 30, blank = True, default = '')
    concern = models.TextField(blank = True, default = '')
    address = models.CharField(max_length = 30, blank = True, default = '')
    intersection = models.CharField(max_length = 30, blank = True, default = '')
    day = models.DateField(blank = True, default = None, null = True)
    time = models.TimeField(blank = True, default = None, null = True)
    frequency = models.PositiveSmallIntegerField(default = 0)
    complainee = models.CharField(max_length = 50, blank = True, default = '')
    complainee_address = models.TextField(blank = True, default = '')
    city = models.CharField(max_length = 20, blank = True, default = '')
    pincode = models.PositiveIntegerField(blank = True, default = 0)#max_length = 6
    phone = models.PositiveIntegerField(blank = True, default = 0)#max_length = 10
    civilian = models.ForeignKey(civilianModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    officer = models.ForeignKey(officerModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    date = models.DateTimeField(default = datetime.now)
    label = models.CharField(max_length = 10, default = 'muted')
    status = models.PositiveSmallIntegerField(default = 0)
    def __str__(self):
        return self.subject

'''
class draftModel(models.Model):
    division = models.ForeignKey(jurisdictionModel, on_delete = models.CASCADE, default = '')
    subject = models.CharField(max_length = 30, default = '')
    concern = models.TextField(default = '')
    address = models.CharField(max_length = 30, default = '')
    intersection = models.CharField(max_length = 30, default = '')
    day = models.DateField(default = 0)
    time = models.TimeField(default = 0)
    frequency = models.PositiveSmallIntegerField(default = 0)
    complainee = models.CharField(max_length = 50, default = '')
    complainee_address = models.TextField(default = '')
    city = models.CharField(max_length = 20, default = '')
    pincode = models.PositiveIntegerField(default = 0)#max_length = 6
    phone = models.PositiveIntegerField(default = 0)#max_length = 10
    email = models.ForeignKey(civilianModel, on_delete = models.CASCADE, default = '')
    date = models.DateTimeField(default = datetime.now)
    status = models.PositiveSmallIntegerField(default = 0)
    def __str__(self):
        return self.subject
'''

login/models.py
from django.db import models

# Create your models here.
class civilianModel(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length = 15)
    # report = models.ForeignKey(reportModel, on_delete = models.CASCADE)#
    first_name = models.CharField(max_length = 20, default = '')
    last_name = models.CharField(max_length = 12, default = '')
    aadhar = models.PositiveIntegerField(default = 0)
    address = models.TextField(default = '')#
    city = models.CharField(max_length = 40, default = '')#
    pincode = models.PositiveIntegerField(default = 0)#
    phone = models.PositiveIntegerField(default = 0)#max_length = 10
    def __str__(self):
        return self.email

from fir.models import jurisdictionModel

class officerModel(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length = 15)
    division = models.ForeignKey(jurisdictionModel, on_delete = models.CASCADE)
    # report = models.ForeignKey(reportModel, on_delete = models.CASCADE)
    def __str__(self):
        return self.email

users/models.py
from datetime import datetime
from django.db import models
from login.models import civilianModel, officerModel

# Create your models here.

class userHistoryModel(models.Model):
    title = models.CharField(max_length = 50, blank = True, default = '')
    civilian = models.ForeignKey(civilianModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    officer = models.ForeignKey(officerModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    datetime = models.DateTimeField(default = datetime.now)
    type = models.BooleanField(default = False)
    issue = models.PositiveSmallIntegerField(default = 0)
    seen = models.BooleanField(default = False)
    def __str__(self):
        return self.title

class userNotificationModel(models.Model):
    title = models.CharField(max_length = 50, blank = True, default = '')
    message = models.CharField(max_length = 150, blank = True, default = '')
    click = models.CharField(max_length = 20, blank = True, default = '')
    civilian = models.ForeignKey(civilianModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    officer = models.ForeignKey(officerModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    datetime = models.DateTimeField(default = datetime.now)
    seen = models.BooleanField(default = False)
    def __str__(self):
        return self.title

users/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.hashers import make_password, check_password
from login.forms import civilianProfileForm
from fir.models import jurisdictionModel, reportModel
from login.models import civilianModel
from users.models import userHistoryModel
from project_fir.methods import create_response, validate_civilian, validate_officer

# Create your views here.
def change_pwd_method(request):
    if validate_civilian(request):
        if request.method  ==  'POST':
            try:
                id = request.session['user_id']
                object = get_object_or_404(civilianModel, pk = id)
                if (check_password(request.POST['password'], object.password) and request.POST['newpassword']  ==  request.POST['repassword']):
                    object.password = make_password(request.POST['newpassword'])
                    object.save()
                    params = create_response('Password Changed Successfully', 2, 'civilian', 'primary', 'check_circle')
                    return render(request, 'respond.html', params)
                params = create_response('Password mismatched.', 0, 'signup_o', 'secondary', 'warning')
                return render(request, 'respond.html', params)
            except:
                params = create_response('Something went wrong:(', 0, 'login_c', 'danger', 'warning')
                return render(request, 'respond.html', params)
        else:
            return render(request, 'change_pwd.html')
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

def civilian_method(request):
    if validate_civilian(request):
        civilian_object = get_object_or_404(civilianModel, pk = request.session['user_id'])
        draft_object = reportModel.objects.filter(civilian = civilian_object.pk, status = 0)
        report_object = reportModel.objects.filter(civilian = civilian_object.pk).exclude(status = 0)
        history_object = userHistoryModel.objects.filter(civilian = civilian_object.pk).order_by('-id')
        to_date = datetime.today()
        params = {'draft_object': draft_object, 'report_object': report_object, 'history_object': history_object, 'to_date': to_date}
        if civilian_object.aadhar:
            params.update({'civilian_object': civilian_object})
        else:
            usermail = civilian_object.email.rsplit('@', 1)
            params.update({'civilian_object': civilian_object, 'usermail': usermail[0]})
        return render(request, 'civilian.html', params)
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

def edit_c_method(request):
    if validate_civilian(request):
        if request.method  ==  'POST':
            civilian_object = get_object_or_404(civilianModel, pk = request.session['user_id'])
            civilian_form = civilianProfileForm(request.POST or None, instance = civilian_object)
            if civilian_form.is_valid():
                try:
                    civilian_form.save()
                    params = create_response('Profile Updated Successfully', 2, 'civilian', 'primary', 'check_circle')
                    return render(request, 'respond.html', params)
                except:
                    params = create_response('Something went wrong:(', 0, 'login_c', 'danger', 'warning')
                    return render(request, 'respond.html', params)
            else:
                params = create_response('Something went wrong:(', 0, 'login_c', 'danger', 'warning')
                return render(request, 'respond.html', params)
        else:
            id = request.session['user_id']
            object = get_object_or_404(civilianModel, pk = id)
            division = jurisdictionModel.objects.all().order_by('division')
            params = {'division': division, 'civilian': object}
            try:
                fir = request.GET['fir']
                params.update({'fir': fir})
            except:
                pass
            return render(request, 'civilian_edit.html', params)
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

def officer_method(request):
    if validate_officer(request):
        return render(request, 'officer.html')
    params = create_response('Access Denied', 3, 'login_o', 'danger', 'warning')
    return render(request, 'respond.html', params)

def test_c_method(request):
    if validate_civilian(request):
        id = request.session['user_id']
        object = get_object_or_404(civilianModel, pk = id)
        params = {'object': object}
        return render(request, 'civilian.html', params)
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

users/templates/change_pwd.html
<!doctype html>
<html lang="en">

<head>
    {% include 'bootstrap/head.html' with title='Change Password' %}
</head>

<body class="bg-primary">

    <!-- navbar -->
    {% include "bootstrap/navbar.html" with navtype=1 home=True about=True %}

    <!-- form -->
    <div class="container" style="max-width:100vh;">
        <div class="row align-items-center" style="min-height:90vh;">
            <div class="col-12">
                <form class="row g-3 needs-validation p-4 mt-5 mb-5" style="background-color:#fff; border-radius:2em;"
                    method="post" novalidate>
                    {% csrf_token %}
                    <div class="col-12">
                        <label for="id_password" class="form-label">Password</label>
                        <input type="password" class="form-control" name="password" minlength="8" maxlength="15"
                            required="" id="id_password" autofocus>
                        <div class="invalid-feedback">
                            Please provide a valid password.
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="id_new_password" class="form-label">New Password</label>
                        <input type="password" class="form-control" name="newpassword" minlength="8" maxlength="15"
                            pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8, }" required="" id="id_new_password">
                        <div class="invalid-feedback">
                            Please provide a valid password.
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="id_re_password" class="form-label">Re-enter New Password</label>
                        <input type="password" class="form-control" name="repassword" minlength="8" maxlength="15"
                            required="" id="id_re_password">
                        <div class="invalid-feedback">
                            Please provide a valid password.
                        </div>
                    </div>
                    <div class="container mt-3">
                        <div class="row text-center">
                            <div class="d-grid col-md-4">
                                <button class="btn btn-primary mb-1 rounded-pill" type="submit" onclick="check()">Change
                                    Password</button>
                            </div>
                            <div class="d-grid col-md-4">
                                <button class="btn btn-primary mb-1 rounded-pill" type="reset">Reset</button>
                            </div>
                            <div class="d-grid col-md-4">
                                <a href="{% url 'civilian' %}" class="btn btn-primary mb-1 rounded-pill">Discard</a>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- <p class="mt-5 mb-3 text-muted">Site under development.</p>
                    <p class="text-muted fixed-bottom pb-3">&copy; 2021–2022</p>
                    <p class="text-muted mb-2" style="position:fixed; bottom:0px; right:10px;">Made with &#10084;
                        on &#127759;.</p> -->
            </div>
        </div>
    </div>

    {% include "scripts/validate.html" %}

    {% include "scripts/js.html" %}
</body>

</html>

users/templates/civilian_edit.html
<!doctype html>
<html lang="en">

<head>
    {% include 'bootstrap/head.html' with title='Edit Profile' %}
</head>

<body class="bg-primary">

    <!-- navbar -->
    {% include "bootstrap/navbar.html" with navtype=1 home=True about=True %}

    <!-- form -->
    <div class="container" style="max-width:100vh;">
        <div class="row align-items-center" style="min-height:90vh;">
            <div class="col-12">
                <form class="row g-3 needs-validation p-4 mt-5 mb-5" style="background-color:#fff; border-radius:2em;"
                    method="post" novalidate>
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="id_first_name" class="form-label">First Name</label>
                        <input type="text" class="form-control" name="first_name" maxlength="20" required=""
                            id="id_first_name" value="{{civilian.first_name}}" autofocus>
                        <div class="invalid-feedback">
                            Please provide a valid first name.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="id_last_name" class="form-label">Last Name</label>
                        <input type="text" class="form-control" name="last_name" maxlength="12" required=""
                            id="id_last_name" value="{{civilian.last_name}}">
                        <div class="invalid-feedback">
                            Please provide a valid last name.
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="id_address" class="form-label">Address</label>
                        <textarea class="form-control" name="address" rows="4" required="" id="id_address"
                            style="resize:none;">{{civilian.address}}</textarea>
                        <div class="invalid-feedback">
                            Please provide a valid address.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="id_city" class="form-label">Nearby Police Division</label>
                        <select class="form-select" name="city" maxlength="40" required="" id="id_city"
                            value="{{civilian.city}}">
                            {% for i in division %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                        <div class="invalid-feedback">
                            Please select a valid division.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="id_pincode" class="form-label">Pincode</label>
                        <input type="text" class="form-control" name="pincode" min="0" required="" id="id_pincode"
                            pattern="[0-9]{6}" value="{{civilian.pincode}}">
                        <div class="invalid-feedback">
                            Please provide a valid pincode.
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="id_aadhar" class="form-label">Aadhar</label>
                        <input type="text" class="form-control" name="aadhar" required="" id="id_aadhar"
                            pattern="[0-9]{12}" value="{{civilian.aadhar}}">
                        <div class="invalid-feedback">
                            Please provide a valid aadhar number.
                        </div>
                    </div>
                    <label for="id_phone" class="form-label mb-0">Mobile</label>
                    <div class="input-group col-12">
                        <span class="input-group-text">+91</span>
                        <input type="tel" class="form-control" name="phone" min="0" required="" id="id_phone"
                            pattern="[6-9]{1}[0-9]{9}" value="{{civilian.phone}}">
                        <div class="invalid-feedback">
                            Please provide a valid mobile number.
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                            <label class="form-check-label" for="invalidCheck">
                                Agree to <a href="{% url 'tac' %}">terms and conditions</a>
                            </label>
                            <div class="invalid-feedback">
                                You must agree before submitting.
                            </div>
                        </div>
                    </div>
                    <div class="container mt-3">
                        <div class="row text-center">
                            <div class="d-grid col-md-4">
                                <button class="btn btn-primary mb-1 rounded-pill" type="submit" onclick="check()">Update Profile</button>
                            </div>
                            <div class="d-grid col-md-4">
                                <button class="btn btn-primary mb-1 rounded-pill" type="reset">Reset</button>
                            </div>
                            <div class="d-grid col-md-4">
                                {% if fir %}
                                <a href="{% url 'report' %}" class="btn btn-primary mb-1 rounded-pill">Discard Changes</a>
                                {% else %}
                                <a href="{% url 'civilian' %}" class="btn btn-primary mb-1 rounded-pill">Discard Changes</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </form>
                <!-- <p class="mt-5 mb-3 text-muted">Site under development.</p>
                    <p class="text-muted fixed-bottom pb-3">&copy; 2021–2022</p>
                    <p class="text-muted mb-2" style="position:fixed; bottom:0px; right:10px;">Made with &#10084;
                        on &#127759;.</p> -->
            </div>
        </div>
    </div>

    {% include "scripts/validate.html" %}

    {% include "scripts/js.html" %}
</body>

</html>

users/templates/civilian_test.html
<!doctype html>
<html lang="en">

<head>
    {% include 'bootstrap/head.html' with title='Civilian' %}

    {% include 'google_icons/icons.html' with outline=True %}
</head>

<body class="bg-light">

    <!-- navbar -->
    {% include "bootstrap/navbar.html" with navtype=2 you=True home=True about=True notification=True %}

    {% include "bootstrap/modal.html" with title="You will be logged out" message="Are you sure you want to logout?" click="logout" close="Close" done="Logout" %}

    {% include "bootstrap/offcanvas.html" %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display:none;">
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
        </symbol>
    </svg>

    <div class="container" style="max-width:100vh;">
        <div class="row" style="min-height:50vh;">
            <div class="col-12 mt-5">
                {% if object.aadhar  ==  0 %}
                <div class="alert alert-primary" role="alert">
                    <div>
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
                            <use xlink:href="#info-fill" />
                        </svg>
                        <h4 class="alert-heading" style="display:inline;">Setup Your Profile</h4>
                    </div>
                </div>
                <div class="alert alert-primary" role="alert">
                    <div>
                        <p>You need to complete your profile setup first in order to register your complaint.</p>
                        <p><a href="{% url 'edit_c' %}" class="alert-link">Click here</a> to complete your profile
                            setup.
                        </p>
                    </div>
                </div>
                <p class="text-center"><kbd class="bg-primary">OR</kbd></p>
                <div class="alert alert-primary" role="alert">
                    <div>
                        <p>Head up to <a href="{% url 'docs' %}" class="alert-link">docs</a> to see how you can update
                            your profile.
                        </p>
                    </div>
                </div>
                {% endif %}

                {% if object.aadhar !=  0 %}
                <div class="d-grid gap-2">
                    <button class="btn btn-primary btn-lg fw-bold fs-5 rounded-pill" type="button">
                        <span class="align-middle material-symbols-outlined">edit</span> Make an FIR
                    </button>
                </div>
                <div class="container mt-3" style="border:0.1em solid #adb5bd; border-radius:1.5em;">
                    <ul class="nav nav-pills nav-fill my-3" id="pills-tab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <button class="nav-link rounded-pill" id="pills-active-tab" data-bs-toggle="pill"
                                data-bs-target="#pills-active" type="button" role="tab" aria-controls="pills-active"
                                aria-selected="false">Active Complaints <span class="badge bg-danger ms-1">4</span>
                            </button>
                        </li>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link rounded-pill" id="pills-history-tab" data-bs-toggle="pill"
                                data-bs-target="#pills-history" type="button" role="tab" aria-controls="pills-history"
                                aria-selected="false">History
                                <span class="text-danger align-middle material-symbols-outlined">
                                    fiber_manual_record
                                </span>
                            </button>
                        </li>
                    </ul>
                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade" id="pills-active" role="tabpanel" aria-labelledby="pills-active-tab"
                            tabindex="0">
                            ...
                        </div>
                        <div class="tab-pane fade" id="pills-history" role="tabpanel"
                            aria-labelledby="pills-history-tab" tabindex="0">
                            ...
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% include "bootstrap/footer.html" %}

    {% include "scripts/js.html" %}
</body>

</html>

users/templates/officer.html
<!doctype html>
<html lang="en">

<head>
    {% include 'bootstrap/head.html' with title='Officer' %}
</head>

<body class="bg-light text-center">

    <!-- navbar -->
    {% include "bootstrap/navbar.html" with navtype=2 you=True home=True about=True %}

    {% include "bootstrap/modal.html" with title="You will be logged out" message="Are you sure you want to logout?" click="logout" close="Close" done="Logout" %}
    
    <div class="container">
        <p>{{user_role}}</p>
        <p>{{user_id}}</p>
    </div>
    
    {% include "bootstrap/footer.html" %}

    {% include "scripts/js.html" %}
</body>

</html>