fir/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_method, name = 'home'), 
    path('create_draft/', views.create_draft_method, name = 'create_draft'), 
    path('update_draft/<int:id>', views.update_draft_method, name = 'update_draft'),
    path('update_draft_lebel/<int:id>', views.update_draft_label_method, name = 'update_draft_label'),
    path('delete_draft/<int:id>', views.delete_draft_method, name = 'delete_draft'),
    path('report/', views.report_method, name = 'report'), 
    path('report/<int:id>', views.report_method, name = 'report_id'), 
]

project_fir/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index_method, name = 'index'), 
    path('about/', views.about_method, name = 'about'), 
    path('admin/', admin.site.urls), 
    path('contact_us/', views.contact_method, name = 'contact'), 
    path('documantation/', views.docs_method, name = 'docs'), 
    path('fir/', include('fir.urls')), 
    path('privacy/', views.privacy_method, name = 'privacy'), 
    path('redirect/', include('login.urls')), 
    path('resources/', views.resources_method, name = 'resources'), 
    path('tac/', views.tac_method, name = 'tac'), 
    path('test/', views.test_method, name = 'test'), 
    path('user/', include('users.urls'))
]

fir/models.py
from datetime import datetime
from django.db import models

# Create your models here.

class jurisdictionModel(models.Model):
    division = models.CharField(max_length = 50)
    def __str__(self):
        return self.division

from login.models import civilianModel, officerModel

class reportModel(models.Model):
    division = models.ForeignKey(jurisdictionModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    subject = models.CharField(max_length = 30, blank = True, default = '')
    concern = models.TextField(blank = True, default = '')
    address = models.CharField(max_length = 30, blank = True, default = '')
    intersection = models.CharField(max_length = 30, blank = True, default = '')
    day = models.DateField(blank = True, default = None, null = True)
    time = models.TimeField(blank = True, default = None, null = True)
    frequency = models.PositiveSmallIntegerField(default = 0)
    complainee = models.CharField(max_length = 50, blank = True, default = '')
    complainee_address = models.TextField(blank = True, default = '')
    city = models.CharField(max_length = 20, blank = True, default = '')
    pincode = models.PositiveIntegerField(blank = True, default = 0)#max_length = 6
    phone = models.PositiveIntegerField(blank = True, default = 0)#max_length = 10
    civilian = models.ForeignKey(civilianModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    officer = models.ForeignKey(officerModel, on_delete = models.CASCADE, blank = True, default = None, null = True)
    date = models.DateTimeField(default = datetime.now)
    label = models.CharField(max_length = 10, default = 'muted')
    status = models.PositiveSmallIntegerField(default = 0)
    def __str__(self):
        return self.subject

'''
class draftModel(models.Model):
    division = models.ForeignKey(jurisdictionModel, on_delete = models.CASCADE, default = '')
    subject = models.CharField(max_length = 30, default = '')
    concern = models.TextField(default = '')
    address = models.CharField(max_length = 30, default = '')
    intersection = models.CharField(max_length = 30, default = '')
    day = models.DateField(default = 0)
    time = models.TimeField(default = 0)
    frequency = models.PositiveSmallIntegerField(default = 0)
    complainee = models.CharField(max_length = 50, default = '')
    complainee_address = models.TextField(default = '')
    city = models.CharField(max_length = 20, default = '')
    pincode = models.PositiveIntegerField(default = 0)#max_length = 6
    phone = models.PositiveIntegerField(default = 0)#max_length = 10
    email = models.ForeignKey(civilianModel, on_delete = models.CASCADE, default = '')
    date = models.DateTimeField(default = datetime.now)
    status = models.PositiveSmallIntegerField(default = 0)
    def __str__(self):
        return self.subject
'''

fir/forms.py
from django import forms
from .models import jurisdictionModel, reportModel

class jurisdictionForm(forms.ModelForm):
    class Meta:
        model = jurisdictionModel
        fields = ['division']

class reportForm(forms.ModelForm):
    class Meta:
        model = reportModel
        # exclude = ['officer', 'date', 'status']
        fields = ['division', 'subject', 'concern', 'address', 'intersection', 'day', 'time', 'frequency', 'complainee', 'complainee_address', 'city', 'pincode', 'phone', 'civilian']

fir/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect, render
from .forms import reportForm
from .models import jurisdictionModel, reportModel
from login.models import civilianModel
from users.models import userHistoryModel
from project_fir.methods import create_response, validate_civilian

def create_draft_method(request):
    if validate_civilian(request):
        draft_form = reportForm(request.POST or None)
        history_obj = userHistoryModel(title = 'You have created a draft "' + request.POST['subject'] +'"', civilian = request.POST['civilian'], datetime = request.POST['date'])
        if draft_form.is_valid():
            draft_form.save()
            history_obj.save()
            return redirect('civilian')
        else:
            params = create_response('Something went wrong:(', 0, 'report', 'danger', 'warning')
            return render(request, 'respond.html', params)
    else:
        params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
        return render(request, 'respond.html', params)

def create_report_method(request):
    pass

def delete_draft_method(request):
    pass

def delete_report_method(request):
    pass

def read_draft_method(request):
    pass

def read_report_method(request):
    pass

def update_draft_method(request, id = 0):
    if validate_civilian(request):
        report_object = get_object_or_404(reportModel, pk = id)
        civilian_object = get_object_or_404(civilianModel, pk = request.session['user_id'])
        if str(report_object.civilian) == str(civilian_object.email):
            if report_object.day is not None:report_object.day = report_object.day.strftime("%Y-%m-%d")
            if report_object.time is not None:report_object.time = report_object.time.strftime("%H:%M")
            division = jurisdictionModel.objects.all().order_by('division')
            draft_form = reportForm(request.POST or None, instance = report_object)
            if draft_form.is_valid():
                draft_form.save()
                time = datetime.now()
                history_obj = userHistoryModel(title = 'You have updated a draft "' + request.POST['subject'] +'"', civilian = civilian_object, datetime = time, issue = 1)
                history_obj.save()
                return redirect('civilian')
            else:
                params = {'report_object': report_object, 'civilian_object': civilian_object, 'division': division, 'update': True}
                return render(request, 'report.html', params)
        else:
            params = create_response('Access Denied', 0, 'civilian', 'danger', 'warning')
            return render(request, 'respond.html', params)
    else:
        params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
        return render(request, 'respond.html', params)

def update_draft_label_method(request, id = 0):
    if validate_civilian(request):
        report_object = get_object_or_404(reportModel, pk = id)
        civilian_object = get_object_or_404(civilianModel, pk = request.session['user_id'])
        if str(report_object.civilian) == str(civilian_object.email):
            report_object.label = request.POST['label']
            print(request.POST['label'])
            report_object.save()
            return redirect('civilian')
        else:
            params = create_response('Access Denied', 0, 'civilian', 'danger', 'warning')
            return render(request, 'respond.html', params)
    else:
        params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
        return render(request, 'respond.html', params)

def home_method(request):
    return render(request, 'home.html')

def report_method(request, id = 0):
    if validate_civilian(request):
        params = {}
        if request.method  ==  'POST':
            pass
        else:
            try:
                report_object = reportModel.objects.get(pk = id)
                report_object.day = report_object.day.strftime("%Y-%m-%d")
                report_object.time = report_object.time.strftime("%H:%M")
                params.update({'report_object': report_object})
            except:
                id = request.session['user_id']
                civilian_object = get_object_or_404(civilianModel, pk = id)
            value = datetime.today()
            division = jurisdictionModel.objects.all().order_by('division')
            params.update({'civilian_object': civilian_object, 'division': division, 'date': value.strftime("%Y-%m-%d"), 'id': id, 'create': True})
            return render(request, 'report.html', params)
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

def draft_method(request):
    if validate_civilian(request):
        if request.method  ==  'POST':
            draft_obj = reportModel.objects.get(pk = request.POST['id'])
            draft_form_obj = reportForm(request.POST or None, instance = draft_obj)
            reportModel.objects.filter(pk = request.POST['id']).update(draft_form_obj)
            # for i in draft_obj:
            #     print(i)
            # for key, value in request.POST.items():
            #     print('Key:%s' % (key) )
            #     print('Value:%s' % (value) )
            # if draft_obj.is_valid():
            try:
                # draft_obj.save()
                params = create_response('Success', 2, 'civilian', 'primary', 'check_circle')
                return render(request, 'respond.html', params)
            # else:
            except:
                params = create_response('Something went wrong:(', 0, 'report', 'danger', 'warning')
                return render(request, 'respond.html', params)
    params = create_response('Access Denied', 3, 'login_c', 'danger', 'warning')
    return render(request, 'respond.html', params)

fir/templates/draft.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>draft</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h1>draft 1.0</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

fir/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'bootstrap/head.html' with title='Home' %}
</head>
<body>
    home 1.0
</body>
</html>

fir/templates/report.html
<!doctype html>
<html lang="en">

<head>
    {% include 'bootstrap/head.html' with title='Report' %}

    {% include "google_icons/icons.html" with opsz=40 weight=400 fill=1 grad=200 %}
</head>

<body class="bg-primary">

    <!-- navbar -->
    {% include "bootstrap/navbar.html" with navtype=1 home=True about=True %}

    <!-- form -->
    <div class="container" style="max-width:100vh;">
        <div class="row align-items-center" style="min-height:90vh;">
            <div class="col-12">
                <form class="needs-validation" method="post" novalidate>
                    {% csrf_token %}
                    <!-- {{form.civilian}}
                    {{form.officer}} -->
                    <div class="display-4 text-white mt-5">Incident Details</div>
                    <div class="row g-3 p-4 mt-3 mb-5" style="background-color:#fff; border-radius:2em;">
                        <div class="col-12">
                            <label for="id_subject" class="form-label">Subject</label>
                            <input type="text" class="form-control" name="subject" maxlength="30" required=""
                                id="id_subject" value="{{report_object.subject}}" autofocus>
                            <div class="invalid-feedback">
                                Please provide a valid subject.
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="id_concern" class="form-label">Concern</label>
                            <textarea class="form-control" name="concern" rows="7" required=""
                                id="id_concern">{{report_object.concern}}</textarea>
                            <div class="invalid-feedback">
                                Please provide a valid concern.
                            </div>
                        </div>
                        <legend>Location</legend>
                        <div class="col-12">
                            <label for="id_address" class="form-label">Address</label>
                            <input type="text" class="form-control" name="address" maxlength="30" required=""
                                id="id_address" value="{{report_object.address}}">
                            <div class="invalid-feedback">
                                Please provide a valid address.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_intersection" class="form-label">Intersection</label>
                            <input type="text" class="form-control" name="intersection" maxlength="30" required=""
                                id="id_intersection" value="{{report_object.intersection}}">
                            <div class="invalid-feedback">
                                Please provide a valid intersection.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_division" class="form-label">Nearby Police Division</label>
                            <select class="form-select" name="division" required="" id="id_division">
                                {% for i in division %}
                                {% if report_object.division  ==  i %}
                                <option value="{{ i.pk }}" selected>{{ i }}</option>
                                {% else %}
                                <option value="{{ i.pk }}">{{ i }}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">
                                Please select a valid police division.
                            </div>
                        </div>
                        {{report_object.day}}
                        <legend>When does the problem occur?</legend>
                        <div class="col-md-6">
                            <label for="id_day" class="form-label">Day</label>
                            <input type="date" class="form-control" name="day" required="" id="id_day"
                                value="{{report_object.day}}">
                            <div class="invalid-feedback">
                                Please provide a valid day.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_time" class="form-label">Time</label>
                            <input type="time" class="form-control" name="time" required="" id="id_time"
                                value="{{report_object.time}}">
                            <div class="invalid-feedback">
                                Please provide a valid time.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_frequency" class="form-label">I have observed this problem or concern</label>
                            <select class="form-select" name="frequency" maxlength="20" required="" id="id_frequency"
                                value="{{report_object.frequency}}">
                                <option value="1">Once</option>
                                <option value="2">More than once</option>
                                <option value="3">Several times</option>
                                <option value="4">Many times</option>
                            </select>
                            <div class="invalid-feedback">
                                Please select a valid frequency.
                            </div>
                        </div>
                    </div>
                    <div class="display-4 text-white">Complainee Details</div>
                    <div class="row g-3 p-4 mt-3 mb-5" style="background-color:#fff; border-radius:2em;">
                        <div>
                            <a href="{% url 'edit_c' %}?fir=True">
                                <span class="float-end text-primary material-symbols-outlined">
                                    edit
                                </span>
                            </a>
                        </div>
                        <div class="col-md-6">
                            <label for="id_complainee" class="form-label">Complainee</label>
                            <input type="text" class="form-control" name="complainee" maxlength="50" required=""
                                id="id_complainee" value="{{civilian_object.first_name}} {{civilian_object.last_name}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a valid complainee.
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="id_complainee_address" class="form-label">Address</label>
                            <textarea class="form-control" name="complainee_address" rows="4" required=""
                                id="id_complainee_address" style="resize:none;" readonly>{{civilian_object.address}}</textarea>
                            <div class="invalid-feedback">
                                Please provide a valid complainee address.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_city" class="form-label">Jurisdiction</label>
                            <input type="text" class="form-control" name="city" min="0" maxlength="20" required=""
                                id="id_city" value="{{civilian_object.city}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a valid city.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_pincode" class="form-label">Pincode</label>
                            <input type="text" class="form-control" name="pincode" min="0" required="" id="id_pincode"
                                pattern="[0-9]{6}" value="{{civilian_object.pincode}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a valid pincode.
                            </div>
                        </div>
                        <label for="id_phone" class="form-label mb-0">Mobile</label>
                        <div class="input-group col-12">
                            <span class="input-group-text">+91</span>
                            <input type="tel" class="form-control rounded-end" name="phone" min="0" required=""
                                id="id_phone" pattern="[6-9]{1}[0-9]{9}" value="{{civilian_object.phone}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a valid mobile number.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_virtual_email" class="form-label">Email</label>
                            <input type="email" class="form-control" name="email" required=""
                                id="id_email" value="{{civilian_object.email}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a email.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="id_date" class="form-label">FIR Registration Date</label>
                            <input type="date" class="form-control" name="date" required="" id="id_date"
                                value="{{date}}" readonly>
                            <div class="invalid-feedback">
                                Please provide a valid date.
                            </div>
                        </div>
                        <input type="text" class="form-control" name="civilian" required=""
                            id="id_civilian" value="{{civilian_object.pk}}" hidden>
                        <!-- <input type="text" class="form-control" name="officer" required=""
                            id="id_officer" value="" hidden> -->
                        <!-- <input type="number" class="form-control" name="id" required=""
                                id="id_id" value="{{id}}" hidden> -->
                        <div class="col-12">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                <label class="form-check-label" for="invalidCheck">
                                    Agree to <a href="{% url 'tac' %}">terms and conditions</a>
                                </label>
                                <div class="invalid-feedback">
                                    You must agree before submitting.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container mb-5">
                        <div class="row text-center">
                            <div class="d-grid col-md-4">
                                <button class="btn bg-white text-primary mb-1 rounded-pill fw-bold" type="submit"
                                    onclick="check()">Register FIR</button>
                            </div>
                            <div class="d-grid col-md-4">
                                <button class="btn bg-white text-primary mb-1 rounded-pill fw-bold"
                                    type="reset">Reset</button>
                            </div>
                            <div class="d-grid col-md-4">
                                {% if create %}
                                <button class="btn bg-white text-primary mb-1 rounded-pill fw-bold" type="submit"
                                    formaction="{% url 'create_draft' %}">Save as Draft</button>
                                    <!-- onclick="this.disabled=true; this.form.action='../create_draft/'; this.form.submit();" -->
                                {% endif %}
                                {% if update %}
                                    <button class="btn bg-white text-primary mb-1 rounded-pill fw-bold" type="submit">Update Draft</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% include "scripts/validate.html" %}

    {% include "scripts/js.html" %}
</body>

</html>